// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/shortener.proto

// Protobuf package name (distinct from Go package)

package shortenerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Info needed to create a shortened URL
type CreateShortenedUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortenedUrlRequest) Reset() {
	*x = CreateShortenedUrlRequest{}
	mi := &file_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortenedUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortenedUrlRequest) ProtoMessage() {}

func (x *CreateShortenedUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortenedUrlRequest.ProtoReflect.Descriptor instead.
func (*CreateShortenedUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortenedUrlRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

// Shortened URL response
type CreateShortenedUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortenedUrl  string                 `protobuf:"bytes,1,opt,name=shortened_url,json=shortenedUrl,proto3" json:"shortened_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortenedUrlResponse) Reset() {
	*x = CreateShortenedUrlResponse{}
	mi := &file_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortenedUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortenedUrlResponse) ProtoMessage() {}

func (x *CreateShortenedUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortenedUrlResponse.ProtoReflect.Descriptor instead.
func (*CreateShortenedUrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortenedUrlResponse) GetShortenedUrl() string {
	if x != nil {
		return x.ShortenedUrl
	}
	return ""
}

// Request to resolve a shortened URL
type ResolveShortenedUrlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The shortened URL to resolve
	ShortenedUrl  string `protobuf:"bytes,1,opt,name=shortened_url,json=shortenedUrl,proto3" json:"shortened_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveShortenedUrlRequest) Reset() {
	*x = ResolveShortenedUrlRequest{}
	mi := &file_proto_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveShortenedUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveShortenedUrlRequest) ProtoMessage() {}

func (x *ResolveShortenedUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveShortenedUrlRequest.ProtoReflect.Descriptor instead.
func (*ResolveShortenedUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveShortenedUrlRequest) GetShortenedUrl() string {
	if x != nil {
		return x.ShortenedUrl
	}
	return ""
}

// Response containing the original URL
type ResolveShortenedUrlResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The original URL corresponding to the shortened URL
	OriginalUrl   string `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveShortenedUrlResponse) Reset() {
	*x = ResolveShortenedUrlResponse{}
	mi := &file_proto_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveShortenedUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveShortenedUrlResponse) ProtoMessage() {}

func (x *ResolveShortenedUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveShortenedUrlResponse.ProtoReflect.Descriptor instead.
func (*ResolveShortenedUrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveShortenedUrlResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

var File_proto_shortener_proto protoreflect.FileDescriptor

const file_proto_shortener_proto_rawDesc = "" +
	"\n" +
	"\x15proto/shortener.proto\x12\fshortener.v1\">\n" +
	"\x19CreateShortenedUrlRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"A\n" +
	"\x1aCreateShortenedUrlResponse\x12#\n" +
	"\rshortened_url\x18\x01 \x01(\tR\fshortenedUrl\"A\n" +
	"\x1aResolveShortenedUrlRequest\x12#\n" +
	"\rshortened_url\x18\x01 \x01(\tR\fshortenedUrl\"@\n" +
	"\x1bResolveShortenedUrlResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl2\xe5\x01\n" +
	"\x10ShortenerService\x12g\n" +
	"\x12CreateShortenedURL\x12'.shortener.v1.CreateShortenedUrlRequest\x1a(.shortener.v1.CreateShortenedUrlResponse\x12h\n" +
	"\x13ResolveShortenedURL\x12'.shortener.v1.CreateShortenedUrlRequest\x1a(.shortener.v1.CreateShortenedUrlResponseB?Z=github.com/Brady-MacDonald/grpc/proto/shortenerv1;shortenerv1b\x06proto3"

var (
	file_proto_shortener_proto_rawDescOnce sync.Once
	file_proto_shortener_proto_rawDescData []byte
)

func file_proto_shortener_proto_rawDescGZIP() []byte {
	file_proto_shortener_proto_rawDescOnce.Do(func() {
		file_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shortener_proto_rawDesc), len(file_proto_shortener_proto_rawDesc)))
	})
	return file_proto_shortener_proto_rawDescData
}

var file_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_shortener_proto_goTypes = []any{
	(*CreateShortenedUrlRequest)(nil),   // 0: shortener.v1.CreateShortenedUrlRequest
	(*CreateShortenedUrlResponse)(nil),  // 1: shortener.v1.CreateShortenedUrlResponse
	(*ResolveShortenedUrlRequest)(nil),  // 2: shortener.v1.ResolveShortenedUrlRequest
	(*ResolveShortenedUrlResponse)(nil), // 3: shortener.v1.ResolveShortenedUrlResponse
}
var file_proto_shortener_proto_depIdxs = []int32{
	0, // 0: shortener.v1.ShortenerService.CreateShortenedURL:input_type -> shortener.v1.CreateShortenedUrlRequest
	0, // 1: shortener.v1.ShortenerService.ResolveShortenedURL:input_type -> shortener.v1.CreateShortenedUrlRequest
	1, // 2: shortener.v1.ShortenerService.CreateShortenedURL:output_type -> shortener.v1.CreateShortenedUrlResponse
	1, // 3: shortener.v1.ShortenerService.ResolveShortenedURL:output_type -> shortener.v1.CreateShortenedUrlResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_shortener_proto_init() }
func file_proto_shortener_proto_init() {
	if File_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shortener_proto_rawDesc), len(file_proto_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shortener_proto_goTypes,
		DependencyIndexes: file_proto_shortener_proto_depIdxs,
		MessageInfos:      file_proto_shortener_proto_msgTypes,
	}.Build()
	File_proto_shortener_proto = out.File
	file_proto_shortener_proto_goTypes = nil
	file_proto_shortener_proto_depIdxs = nil
}
